package com.demo.common.model;

import com.demo.common.model.base.BaseSmsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsInfo extends BaseSmsInfo<SmsInfo> {
	public static final SmsInfo dao = new SmsInfo();
}
