package com.demo.common.model;

import com.demo.common.model.base.BaseSmsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsInfo extends BaseSmsInfo<SmsInfo> {
	public static final SmsInfo dao = new SmsInfo();
	
	public boolean isExistCode(String phone,String code){
		SmsInfo info = dao.findFirst("select * from sms_info where phone = '"+phone+"' order by id desc");
		if(null!=info && code.equals(info.getCode())){
			return true;
		}
		return false;
	}
}
