package com.demo.common.model;

import com.demo.common.model.base.BaseValueInfo;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ValueInfo extends BaseValueInfo<ValueInfo> {
	public static final ValueInfo dao = new ValueInfo();
	
	public Page<ValueInfo> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from value_info order by sort desc");
	}
}
